# Generated by Django 3.1.3 on 2020-11-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_Zipcode',
            field=models.IntegerField(default='+171717'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_phonenumber',
            field=models.IntegerField(default='+1717176171717'),
        ),
    ]
