# Generated by Django 3.1.3 on 2020-11-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpanel', '0002_auto_20201123_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(default='', max_length=100)),
                ('agent_username', models.CharField(default='', max_length=100)),
                ('agent_password', models.CharField(default='', max_length=100)),
                ('agent_address', models.CharField(default='', max_length=100)),
                ('agent_phonenumber', models.IntegerField(default='+1717176171717')),
            ],
        ),
    ]
