# Generated by Django 3.1.3 on 2020-11-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarpanel', '0003_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solarpanel.agents'),
        ),
    ]
